name: 'project_builder'
version: 1.0.1
description: A scaffolding generator for dart project from custom templates.
author: Borut Jegrisnik <borut@medianova.hr>
homepage: https://github.com/Medianova/project_builder

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: "^0.13.2"
  ansicolor: "^0.0.9"

# executables:
#   builder:
